### PR TITLE
Lunch.js with raining food emojis

### PR DESCRIPTION
**Pull request by seanwestfall**
Since not everybody liked the idea of adding angular to the lunch.js website, here another idea. Based on the Donutjs.club website. @machikoyasuda suggested it.

```bash
$ npm i
$ npm start
```

Screenshot:
siklzlyxr7

### CODE REVIEW

**Comment by davidguttman** [comment]
Fun!

**Comment by davidguttman** [comment]
Now that the actual site code is on GH, go ahead and rebase/fix conflicts and I'll take a look.

**Comment by gnarmedia** [comment]
I love this.

**Comment by gr2m** [comment]
this would need to be redone based on latest master. I'd suggest to send a new pull request and close this one as it's been open for over a year?

**Comment by davidguttman** [comment]
Sounds good, closing.

**Pull request closed without merging**
