### PR TITLE
Convert Site to Gatsby

### PR DESCRIPTION
**Pull request by anguspiv**
Updating the site from a basic HTML page with sass files to a full Gatsby Site

The thinking behind this is to support future potential features like display locations / github issues on the site itself to make it readily easy to find them. 

Totally not offended, if we think this is overkill.

### CODE REVIEW

**Comment by anguspiv** [comment]
Okay, there is a build error. The card is not displaying, but I am not able to replicate it. So looking to fix

**Comment by MrBenJ** [comment]
Hey @anguspiv - I think this is super overkill. I'm looking at the previous lunch.js site and what we have on your branch, and I don't think it's really necessary.

Even with Gatsby, we'd need to link up Github's API to Gatsby's GraphQL API and then deliver that to the page. It seems like total overkill and way too complex. 

In short, I don't think we need to migrate away from a static site until things get more complex with Lunch.js. I don't see why we can't just have the static page make the API calls directly in a plain old `<script>` tag. If we wanted to display Github issues and locations on the page itself.

Then again, this is just an opinion, and you're the owner of this portion of jsla. Whatever decision you choose to make, I support it.

**Comment by gr2m** [comment]
I second @MrBenJ

**Comment by anguspiv** [comment]
Even though I am the project owner, that's for now. So Even what I want to add I want a consensus on, just in case someone has to come behind me to work on it. 

Yeah, I agree with you both, @MrBenJ and @gr2m  I kinda realized that a little late... I got distracted by the shiny new thing.

I was mostly thinking something that could help me rewrite the markdown docs as new pages quickly, add a nav, and pull the locations in, all at once.  So I will start smaller with a few changes that will come in shortly....

**Pull request closed without merging**
